C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Source/Data.cpp File Reference
#include `../headers/Data.h`
*
Functions
ostream & operator<< (ostream &os, const Data &data)
Function Documentation
ostream& operator<< (ostream & os, const Data & data)
Definition at line 174 of file Data.cpp.
References Data::getAno(), Data::getDia(), and Data::getMes().