C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Source/Veiculo.cpp File Reference
#include `../headers/Veiculo.h`
*
Functions
ostream & operator<< (ostream &os, const Veiculo &veiculo)
ostream & operator<< (ostream &os, Veiculo *veiculo)
Function Documentation
ostream& operator<< (ostream & os, const Veiculo & veiculo)
Definition at line 343 of file Veiculo.cpp.
References Veiculo::getMarca(), and Veiculo::getModelo().
ostream& operator<< (ostream & os, Veiculo * veiculo)
Definition at line 348 of file Veiculo.cpp.
References Veiculo::getMarca(), and Veiculo::getModelo().