Empresa Class Reference
Classe derivada da classe mãe Membro.
#include <Empresa.h>
Public Member Functions
Empresa ()
Empresa (const string &nome, const string &utilizador, const string &password, const string &website)
Construtor por defeito da classe.
void signup ()
Construtor com parâmetros da classe.
void edit ()
Função que cria um novo website.
void save (ofstream &file, vector< Combustivel > *combustiveis)
Função que permite editar a informação de um website.
void show () const
Função que grava a informação relativa a uma empresa.
Private Attributes
string website
Additional Inherited Members
Detailed Description
Classe derivada da classe mãe Membro.
Definition at line 10 of file Empresa.h.
Constructor & Destructor Documentation
Empresa::Empresa ()
Definition at line 3 of file Empresa.cpp.
Empresa::Empresa (const string & nome, const string & utilizador, const string & password, const string & website)
Construtor por defeito da classe.
Definition at line 8 of file Empresa.cpp.
References website.
Member Function Documentation
void Empresa::edit () [virtual]
Função que cria um novo website.
Reimplemented from Membro.
Definition at line 20 of file Empresa.cpp.
References Membro::edit(), InputUtils::readYesOrNo(), and website.
void Empresa::save (ofstream & file, vector< Combustivel > * combustiveis) [virtual]
Função que permite editar a informação de um website.
Reimplemented from Membro.
Definition at line 31 of file Empresa.cpp.
References Membro::save().
void Empresa::show () const [virtual]
Função que grava a informação relativa a uma empresa.
Reimplemented from Membro.
Definition at line 37 of file Empresa.cpp.
References Membro::show(), and website.
void Empresa::signup () [virtual]
Construtor com parâmetros da classe.
Implements Membro.
Definition at line 14 of file Empresa.cpp.
References InputUtils::readLine(), and website.
Member Data Documentation
string Empresa::website [private]
Definition at line 12 of file Empresa.h.
Referenced by edit(), Empresa(), show(), and signup().
The documentation for this class was generated from the following files:
Empresa.h
Empresa.cpp