Data Class Reference
#include <Data.h>
Public Member Functions
Data ()
Data (unsigned dia, unsigned mes, unsigned ano)
Construtor por defeito da classe.
unsigned getDia () const
Construtor com parametros da classe.
unsigned getMes () const
método para retornar o parametro dia de uma data
unsigned getAno () const
método para retornar o parametro mes de uma data
void setDia (unsigned dia)
metodo para retornar o paramentro ano de uma data
void setMes (unsigned mes)
método para alterar o dia de uma data
void setAno (unsigned ano)
metodo para alterar o mes de uma data
bool operator< (const Data &data) const
metodo para alterar o ano de uma data
void save (ofstream &file)
Overload do operador < para comparar datas.
void load (ifstream &file)
Função que grava a informação relativa a uma data no ficheiro correspondente.
void criar ()
Função que carrega a informação relativa a uma data para a execução de um programa.
void editar ()
Função que permite criar uma nova data.
bool isBissexto () const
Função que permite editar uma data ja existente.
bool operator== (const Data &data) const
Função que verifica se um ano é bissexto e retorna true caso seja verdade.
Protected Attributes
unsigned int dia
unsigned int mes
unsigned int ano
Friends
ostream & operator<< (ostream &os, const Data &data)
Overload do operador de igualdade para que seja possivel comparar datas.
Detailed Description
Definition at line 9 of file Data.h.
Constructor & Destructor Documentation
Data::Data ()
Definition at line 3 of file Data.cpp.
Data::Data (unsigned dia, unsigned mes, unsigned ano)
Construtor por defeito da classe.
Definition at line 8 of file Data.cpp.
References ano, dia, and mes.
Member Function Documentation
void Data::criar ()
Função que carrega a informação relativa a uma data para a execução de um programa.
Definition at line 95 of file Data.cpp.
References ano, dia, InvalidInputException< T >::info, DataInvalidaException< T >::info, isBissexto(), mes, and InputUtils::readInt().
Referenced by Anuncio::criar(), and editar().
void Data::editar ()
Função que permite criar uma nova data.
Definition at line 154 of file Data.cpp.
References criar().
Referenced by Anuncio::editar().
unsigned Data::getAno () const
método para retornar o parametro mes de uma data
Definition at line 25 of file Data.cpp.
References ano.
Referenced by operator<(), and operator<<().
unsigned Data::getDia () const
Construtor com parametros da classe.
Definition at line 15 of file Data.cpp.
References dia.
Referenced by operator<(), and operator<<().
unsigned Data::getMes () const
método para retornar o parametro dia de uma data
Definition at line 20 of file Data.cpp.
References mes.
Referenced by operator<(), and operator<<().
bool Data::isBissexto () const
Função que permite editar uma data ja existente.
Definition at line 159 of file Data.cpp.
References ano.
Referenced by criar().
void Data::load (ifstream & file)
Função que grava a informação relativa a uma data no ficheiro correspondente.
Definition at line 85 of file Data.cpp.
References ano, dia, and mes.
Referenced by Boleia::load(), and Anuncio::load().
bool Data::operator< (const Data & data) const
metodo para alterar o ano de uma data
Definition at line 48 of file Data.cpp.
References getAno(), getDia(), and getMes().
bool Data::operator== (const Data & data) const
Função que verifica se um ano é bissexto e retorna true caso seja verdade.
Definition at line 169 of file Data.cpp.
References ano, dia, and mes.
void Data::save (ofstream & file)
Overload do operador < para comparar datas.
Definition at line 78 of file Data.cpp.
References ano, dia, and mes.
Referenced by Boleia::save(), and Anuncio::save().
void Data::setAno (unsigned ano)
metodo para alterar o mes de uma data
Definition at line 42 of file Data.cpp.
References ano.
void Data::setDia (unsigned dia)
metodo para retornar o paramentro ano de uma data
Definition at line 30 of file Data.cpp.
References dia.
void Data::setMes (unsigned mes)
método para alterar o dia de uma data
Definition at line 36 of file Data.cpp.
References mes.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Data & data) [friend]
Overload do operador de igualdade para que seja possivel comparar datas.
Definition at line 174 of file Data.cpp.
Member Data Documentation
unsigned int Data::ano [protected]
Definition at line 14 of file Data.h.
Referenced by criar(), Data(), getAno(), isBissexto(), load(), operator==(), save(), and setAno().
unsigned int Data::dia [protected]
Definition at line 12 of file Data.h.
Referenced by criar(), Data(), getDia(), load(), operator==(), save(), and setDia().
unsigned int Data::mes [protected]
Definition at line 13 of file Data.h.
Referenced by criar(), Data(), getMes(), load(), operator==(), save(), and setMes().
The documentation for this class was generated from the following files:
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Headers/Data.h
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Source/Data.cpp