Hora Class Reference
#include <Hora.h>
Public Member Functions
Hora ()
void show () const
Construtor por defeito da classe.
Hora (unsigned hora, unsigned minuto)
Função que permite mostrar na Consola a informação referente a uma hora.
unsigned getHora () const
Construtor com parâmetros da classe.
unsigned getMinuto () const
Método para retornar a hora.
void setHora (unsigned hora)
Método para retornar os minutos.
void setMinuto (unsigned minuto)
Método para alterar a hora.
bool operator< (const Hora &horas)
Método para alterar os minutos.
void save (ofstream &file)
Overload do operadro < de forma a se puder comparar horas.
void load (ifstream &file)
Função responsavel por gravar as informações relativas as hora no respectivo ficheiro.
void criar ()
Função responsavel por descarregar a informação de um ficheiro sobre as horas.
void editar ()
Função para criar uma nova hora.
Private Attributes
unsigned hora
unsigned minuto
Friends
ostream & operator<< (ostream &os, const Hora &hora)
Função para editar as informações referentes a uma hora ja existente.
Detailed Description
Definition at line 9 of file Hora.h.
Constructor & Destructor Documentation
Hora::Hora ()
Definition at line 3 of file Hora.cpp.
Hora::Hora (unsigned hora, unsigned minuto)
Função que permite mostrar na Consola a informação referente a uma hora.
Definition at line 8 of file Hora.cpp.
References hora, and minuto.
Member Function Documentation
void Hora::criar ()
Função responsavel por descarregar a informação de um ficheiro sobre as horas.
Definition at line 73 of file Hora.cpp.
References hora, InvalidInputException< T >::info, minuto, and InputUtils::readInt().
Referenced by Anuncio::criar(), and editar().
void Hora::editar ()
Função para criar uma nova hora.
Definition at line 104 of file Hora.cpp.
References criar().
Referenced by Anuncio::editar().
unsigned Hora::getHora () const
Construtor com parâmetros da classe.
Definition at line 14 of file Hora.cpp.
References hora.
Referenced by operator<().
unsigned Hora::getMinuto () const
Método para retornar a hora.
Definition at line 19 of file Hora.cpp.
References minuto.
Referenced by operator<().
void Hora::load (ifstream & file)
Função responsavel por gravar as informações relativas as hora no respectivo ficheiro.
Definition at line 60 of file Hora.cpp.
References hora, and minuto.
Referenced by Boleia::load(), and Anuncio::load().
bool Hora::operator< (const Hora & horas)
Método para alterar os minutos.
Definition at line 34 of file Hora.cpp.
References getHora(), and getMinuto().
void Hora::save (ofstream & file)
Overload do operadro < de forma a se puder comparar horas.
Definition at line 54 of file Hora.cpp.
References hora, and minuto.
Referenced by Boleia::save(), and Anuncio::save().
void Hora::setHora (unsigned hora)
Método para retornar os minutos.
Definition at line 24 of file Hora.cpp.
References hora.
void Hora::setMinuto (unsigned minuto)
Método para alterar a hora.
Definition at line 29 of file Hora.cpp.
References minuto.
void Hora::show () const
Construtor por defeito da classe.
Definition at line 68 of file Hora.cpp.
References hora, and minuto.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Hora & hora) [friend]
Função para editar as informações referentes a uma hora ja existente.
Definition at line 109 of file Hora.cpp.
Member Data Documentation
unsigned Hora::hora [private]
Definition at line 12 of file Hora.h.
Referenced by criar(), getHora(), Hora(), load(), operator<<(), save(), setHora(), and show().
unsigned Hora::minuto [private]
Definition at line 13 of file Hora.h.
Referenced by criar(), getMinuto(), Hora(), load(), operator<<(), save(), setMinuto(), and show().
The documentation for this class was generated from the following files:
Hora.h
Hora.cpp