Membro Class Reference
#include <Membro.h>
Public Member Functions
Membro ()
Membro (string nome, string utilizador, string password)
Construtor por defeito da classe.
string getNome () const
Construtor com parametros da classe.
string getUtilizador () const
Método para retornar o nome do membro.
string getPassword () const
Método para retornar o utilizador do membro.
vector< Veiculo * > getVeiculos ()
Método para retornar a password do membro.
void setNome (string &nome)
Método para retornar os veiculos associados a um membro.
void setUtilizador (string &utilizador)
Método para alterar o nome de um membro.
void setPassword (string &password)
Método para alterar o utilizador de um membro.
void setVeiculos (const vector< Veiculo > &veiculo)
Método para alterar a password e um membro.
void addVeiculo (Veiculo veiculo)
Método para alterar os veiculos associados a um membro.
void removeVeiculo (Veiculo *veiculo)
Função para adicionar um veiculo ao vector de veiculos.
void load (ifstream &file, vector< Combustivel > *combustiveis)
Função para remover um veiculo.
virtual void save (ofstream &file, vector< Combustivel > *combustiveis)
Função para carregar a informação de um membro.
virtual void signup ()=0
Função para gravar a informação de um membro no ficheiro de membros.
virtual void edit ()
Função abstrata para criar um novo utilizador da API.
virtual void updateConhecidos (vector< Membro * > passageiros)
Função virtual para editar a informação relativa a um membro.
virtual void show () const
bool temVeiculo () const
Função para imprimir no ecrã toda a informação relativa a um membro.
bool operator== (const Membro &membro1) const
Função para confirmar se um membro tem veiculos(retorna true caso se confirme)
Protected Attributes
string nome
string utilizador
string password
vector< Veiculo > veiculos
Detailed Description
Definition at line 13 of file Membro.h.
Constructor & Destructor Documentation
Membro::Membro ()
Definition at line 3 of file Membro.cpp.
Membro::Membro (string nome, string utilizador, string password)
Construtor por defeito da classe.
Definition at line 8 of file Membro.cpp.
References nome, password, and utilizador.
Member Function Documentation
void Membro::addVeiculo (Veiculo veiculo)
Método para alterar os veiculos associados a um membro.
Definition at line 55 of file Membro.cpp.
References veiculos.
Referenced by BoleiasInteligentes::showVeiculosMenu().
void Membro::edit () [virtual]
Função abstrata para criar um novo utilizador da API.
Reimplemented in Empresa.
Definition at line 77 of file Membro.cpp.
References nome, password, and InputUtils::readYesOrNo().
Referenced by Empresa::edit(), and BoleiasInteligentes::showMainMenu().
string Membro::getNome () const
Construtor com parametros da classe.
Definition at line 15 of file Membro.cpp.
References nome.
Referenced by Anuncio::show().
string Membro::getPassword () const
Método para retornar o utilizador do membro.
Definition at line 35 of file Membro.cpp.
References password.
string Membro::getUtilizador () const
Método para retornar o nome do membro.
Definition at line 20 of file Membro.cpp.
References utilizador.
Referenced by BoleiasInteligentes::showLoginMenu().
vector< Veiculo * > Membro::getVeiculos ()
Método para retornar a password do membro.
Definition at line 25 of file Membro.cpp.
References veiculos.
Referenced by AnuncioOferta::criar(), Boleia::load(), Anuncio::load(), Boleia::save(), Anuncio::save(), BoleiasInteligentes::showAnunciosMenu(), and BoleiasInteligentes::showVeiculosMenu().
void Membro::load (ifstream & file, vector< Combustivel > * combustiveis)
Função para remover um veiculo.
Definition at line 93 of file Membro.cpp.
References Veiculo::load(), nome, password, utilizador, and veiculos.
Referenced by BoleiasInteligentes::loadMembros().
bool Membro::operator== (const Membro & membro1) const
Função para confirmar se um membro tem veiculos(retorna true caso se confirme)
Definition at line 72 of file Membro.cpp.
References utilizador.
void Membro::removeVeiculo (Veiculo * veiculo)
Função para adicionar um veiculo ao vector de veiculos.
Definition at line 60 of file Membro.cpp.
References veiculos.
Referenced by BoleiasInteligentes::showVeiculosMenu().
void Membro::save (ofstream & file, vector< Combustivel > * combustiveis) [virtual]
Função para carregar a informação de um membro.
Reimplemented in Particular, and Empresa.
Definition at line 109 of file Membro.cpp.
References nome, password, utilizador, and veiculos.
Referenced by Empresa::save(), and Particular::save().
void Membro::setNome (string & nome)
Método para retornar os veiculos associados a um membro.
Definition at line 40 of file Membro.cpp.
References nome.
Referenced by BoleiasInteligentes::showLoginMenu().
void Membro::setPassword (string & password)
Método para alterar o utilizador de um membro.
Definition at line 45 of file Membro.cpp.
References password.
Referenced by BoleiasInteligentes::showLoginMenu().
void Membro::setUtilizador (string & utilizador)
Método para alterar o nome de um membro.
Definition at line 50 of file Membro.cpp.
References utilizador.
Referenced by BoleiasInteligentes::showLoginMenu().
void Membro::setVeiculos (const vector< Veiculo > & veiculo)
Método para alterar a password e um membro.
void Membro::show () const [virtual]
Reimplemented in Empresa.
Definition at line 121 of file Membro.cpp.
References nome, and utilizador.
Referenced by Empresa::show(), and Boleia::show().
virtual void Membro::signup () [pure virtual]
Função para gravar a informação de um membro no ficheiro de membros.
Implemented in Particular, and Empresa.
Referenced by BoleiasInteligentes::showLoginMenu().
bool Membro::temVeiculo () const
Função para imprimir no ecrã toda a informação relativa a um membro.
Definition at line 127 of file Membro.cpp.
References veiculos.
void Membro::updateConhecidos (vector< Membro * > passageiros) [virtual]
Função virtual para editar a informação relativa a um membro.
Reimplemented in Particular.
Definition at line 132 of file Membro.cpp.
Member Data Documentation
string Membro::nome [protected]
Definition at line 16 of file Membro.h.
Referenced by edit(), getNome(), load(), Membro(), save(), setNome(), Particular::show(), and show().
string Membro::password [protected]
Definition at line 18 of file Membro.h.
Referenced by edit(), getPassword(), load(), Membro(), save(), and setPassword().
string Membro::utilizador [protected]
Definition at line 17 of file Membro.h.
Referenced by getUtilizador(), load(), Membro(), operator==(), save(), setUtilizador(), Particular::show(), and show().
vector<Veiculo> Membro::veiculos [protected]
Definition at line 19 of file Membro.h.
Referenced by addVeiculo(), getVeiculos(), load(), removeVeiculo(), save(), Particular::show(), and temVeiculo().
The documentation for this class was generated from the following files:
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Headers/Membro.h
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Source/Membro.cpp