Anuncio Class Reference
#include <Anuncio.h>
Public Member Functions
Anuncio ()
Anuncio (const string &titulo, const string &descricao, const Coordenadas &origem, const Coordenadas &destino, const Data &dataInicio, const Data &dataFim)
Construtor sem parâmetros.
string getTitulo () const
Construtor com parâmetros.
string getDescricao () const
Método para obter o titulo do anuncio.
Membro * getAnunciante () const
Método para obter a descrição do anuncio.
void setTitulo (const string &titulo)
Método para obter o membro responsavel pelo Anuncio.
void setVeiculo (Veiculo *veiculo)
Método para alterar o titulo.
Veiculo * getVeiculo ()
Método para alteras as informações do veículo.
Membro * getCondutor ()
Método para obter o veiculo do Anuncio.
Preco * getPreco ()
Método para obter o condutor do veiculo.
Hora getHora () const
Método para obter o preço discriminado do Anuncio de Boleia.
Data getDataInicio () const
Método para obter a hora de inicio da Boleia.
Data getDataFim () const
Método para obter a data de inicio do anuncio.
vector< Particular * > getPassageiros ()
Método para obter a data de fim do anuncio.
void setCondutor (Membro *membro)
Método para obter os passageiros ja instalados no veiculo.
void setPreco (const Preco &preco)
Método para alterar o condutor.
Coordenadas getOrigem ()
Método para alterar o preço do anuncio.
Coordenadas getDestino ()
Método que retorna as coordenadas do local de inicio da Boleia.
void setDescricao (const string &descricao)
Método que retorna as coordenadas do local onde termina a Boleia.
void setAnunciante (Membro *membro)
Método para alterar a descrição do anuncio.
void addPassageiro (Particular *membro)
Método para alterar o anunciante.
void calcularPrecoTotal ()
Função para adicionar um passageiro á viagem.
virtual void show () const
Função para calcular o preço final com todos os custos ja associados.
virtual void load (ifstream &file, vector< Membro * > *membros)
Função que mostra no ecrã da consola toda a informação de um determinado anuncio.
virtual void save (ofstream &file, vector< Membro * > *membros)
Função virtual que carrega de um ficheiro para o vector toda a informação do anuncio.
virtual void criar (Membro *utilizadorAtual)
Função virtual que grava a informação do anuncio no ficheiro de anuncios.
virtual void editar ()=0
Função virtual responsavel por criar um anuncio.
bool isPronto () const
Função responsavel por editar as componentes de um anuncio.
virtual bool podeSerPassageiro (Membro *membro) const
Funçao que confirma se o anuncio já tem condutor e veiculo,ou seja, se já está pronto para começar a viagem.
virtual bool podeSerCondutor (Membro *membro) const
Função responsavel por determinar se um determinado membro é passageiro.Se o for retorna true.
virtual void updateConhecidos ()
Funçao responsavel por determinar se um determinado membro é condutor.Se o for retorna true.
double calcularFriendPoints (const Particular *utilizadorAtual) const
Função que da update aos conhecidos.
double calcularDistanciaPoints (const Coordenadas &origem, const Coordenadas &destino) const
Função que calcula os pontos obtidos por um membro de acordo com os conhecidos que posssui e com o numero de vezes que ja viajou com cada conhecido.
double calcularAnuncioPoints (const Particular *utilizadorAtual, const Coordenadas &origem, const Coordenadas &destino) const
Função chave para organizar os anuncios por distância pois organiza os pontos atribuidos de acordo com a distancia a que esta do utilizador.
Protected Attributes
string titulo
string descricao
Coordenadas origem
Coordenadas destino
vector< Particular * > passageiros
Data dataInicio
Número total de pessoas no veículo = passageiros + 1 (condutor)
Data dataFim
Membro * anunciante
se for igual ao inicio é um evento
Membro * condutor
Veiculo * veiculo
Preco preco
Hora hora
Friends
ostream & operator<< (ostream &os, Anuncio *anuncio)
Calcula o rsultado final entre os friend points e a distancia para ordenar os anuncios.
Detailed Description
Definition at line 18 of file Anuncio.h.
Constructor & Destructor Documentation
Anuncio::Anuncio ()
Definition at line 3 of file Anuncio.cpp.
Anuncio::Anuncio (const string & titulo, const string & descricao, const Coordenadas & origem, const Coordenadas & destino, const Data & dataInicio, const Data & dataFim)
Construtor sem parâmetros.
Definition at line 8 of file Anuncio.cpp.
Member Function Documentation
void Anuncio::addPassageiro (Particular * membro)
Método para alterar o anunciante.
Definition at line 103 of file Anuncio.cpp.
References passageiros.
double Anuncio::calcularAnuncioPoints (const Particular * utilizadorAtual, const Coordenadas & origem, const Coordenadas & destino) const
Função chave para organizar os anuncios por distância pois organiza os pontos atribuidos de acordo com a distancia a que esta do utilizador.
Definition at line 435 of file Anuncio.cpp.
References calcularDistanciaPoints(), and calcularFriendPoints().
double Anuncio::calcularDistanciaPoints (const Coordenadas & origem, const Coordenadas & destino) const
Função que calcula os pontos obtidos por um membro de acordo com os conhecidos que posssui e com o numero de vezes que ja viajou com cada conhecido.
Definition at line 430 of file Anuncio.cpp.
References Coordenadas::calcDistancia().
Referenced by calcularAnuncioPoints().
double Anuncio::calcularFriendPoints (const Particular * utilizadorAtual) const
Função que da update aos conhecidos.
sqrt() to make sure the number doesn't grow too fast
Definition at line 402 of file Anuncio.cpp.
References condutor, Particular::getConhecidos(), and passageiros.
Referenced by calcularAnuncioPoints().
void Anuncio::calcularPrecoTotal ()
Função para adicionar um passageiro á viagem.
void Anuncio::criar (Membro * utilizadorAtual) [virtual]
Função virtual que grava a informação do anuncio no ficheiro de anuncios.
Reimplemented in AnuncioProcura, and AnuncioOferta.
Definition at line 257 of file Anuncio.cpp.
References anunciante, Hora::criar(), Coordenadas::criar(), Data::criar(), dataFim, dataInicio, descricao, destino, hora, origem, and titulo.
Referenced by AnuncioOferta::criar(), AnuncioProcura::criar(), and BoleiasInteligentes::showAnunciosMenu().
void Anuncio::editar () [pure virtual]
Função virtual responsavel por criar um anuncio.
Implemented in AnuncioProcura, and AnuncioOferta.
Definition at line 276 of file Anuncio.cpp.
References dataFim, dataInicio, descricao, destino, Hora::editar(), Coordenadas::editar(), Data::editar(), hora, InvalidInputException< T >::info, origem, InputUtils::readLine(), InputUtils::readYesOrNo(), and titulo.
Referenced by AnuncioOferta::editar(), and AnuncioProcura::editar().
Membro * Anuncio::getAnunciante () const
Método para obter a descrição do anuncio.
Definition at line 93 of file Anuncio.cpp.
References anunciante.
Membro * Anuncio::getCondutor ()
Método para obter o veiculo do Anuncio.
Definition at line 38 of file Anuncio.cpp.
References condutor.
Data Anuncio::getDataFim () const
Método para obter a data de inicio do anuncio.
Definition at line 83 of file Anuncio.cpp.
References dataFim.
Data Anuncio::getDataInicio () const
Método para obter a hora de inicio da Boleia.
Definition at line 78 of file Anuncio.cpp.
References dataInicio.
string Anuncio::getDescricao () const
Método para obter o titulo do anuncio.
Definition at line 18 of file Anuncio.cpp.
References descricao.
Coordenadas Anuncio::getDestino ()
Método que retorna as coordenadas do local de inicio da Boleia.
Definition at line 63 of file Anuncio.cpp.
References destino.
Referenced by BoleiasInteligentes::showAnunciosMenu().
Hora Anuncio::getHora () const
Método para obter o preço discriminado do Anuncio de Boleia.
Definition at line 73 of file Anuncio.cpp.
References hora.
Coordenadas Anuncio::getOrigem ()
Método para alterar o preço do anuncio.
Definition at line 58 of file Anuncio.cpp.
References origem.
Referenced by BoleiasInteligentes::showAnunciosMenu().
vector< Particular * > Anuncio::getPassageiros ()
Método para obter a data de fim do anuncio.
Definition at line 68 of file Anuncio.cpp.
References passageiros.
Preco * Anuncio::getPreco ()
Método para obter o condutor do veiculo.
Definition at line 43 of file Anuncio.cpp.
References preco.
Referenced by BoleiasInteligentes::showAnunciosMenu().
string Anuncio::getTitulo () const
Construtor com parâmetros.
Definition at line 13 of file Anuncio.cpp.
References titulo.
Referenced by operator<<().
Veiculo * Anuncio::getVeiculo ()
Método para alteras as informações do veículo.
Definition at line 33 of file Anuncio.cpp.
References veiculo.
Referenced by BoleiasInteligentes::showAnunciosMenu().
bool Anuncio::isPronto () const
Função responsavel por editar as componentes de um anuncio.
Definition at line 340 of file Anuncio.cpp.
References condutor, and veiculo.
void Anuncio::load (ifstream & file, vector< Membro * > * membros) [virtual]
Função que mostra no ecrã da consola toda a informação de um determinado anuncio.
Reimplemented in AnuncioProcura.
Definition at line 137 of file Anuncio.cpp.
References anunciante, condutor, dataFim, dataInicio, descricao, destino, Membro::getVeiculos(), hora, Hora::load(), Data::load(), Coordenadas::load(), Preco::load(), origem, passageiros, preco, titulo, and veiculo.
Referenced by AnuncioProcura::load(), and BoleiasInteligentes::loadAnuncios().
bool Anuncio::podeSerCondutor (Membro * membro) const [virtual]
Função responsavel por determinar se um determinado membro é passageiro.Se o for retorna true.
Reimplemented in AnuncioProcura.
Definition at line 374 of file Anuncio.cpp.
References condutor, and passageiros.
Referenced by AnuncioProcura::podeSerCondutor().
bool Anuncio::podeSerPassageiro (Membro * membro) const [virtual]
Funçao que confirma se o anuncio já tem condutor e veiculo,ou seja, se já está pronto para começar a viagem.
Reimplemented in AnuncioProcura.
Definition at line 349 of file Anuncio.cpp.
References condutor, Veiculo::getLotacao(), passageiros, and veiculo.
Referenced by AnuncioProcura::podeSerPassageiro().
void Anuncio::save (ofstream & file, vector< Membro * > * membros) [virtual]
Função virtual que carrega de um ficheiro para o vector toda a informação do anuncio.
Reimplemented in AnuncioProcura.
Definition at line 185 of file Anuncio.cpp.
References anunciante, condutor, dataFim, dataInicio, descricao, destino, Membro::getVeiculos(), hora, origem, passageiros, preco, Hora::save(), Data::save(), Coordenadas::save(), Preco::save(), titulo, and veiculo.
Referenced by AnuncioProcura::save().
void Anuncio::setAnunciante (Membro * membro)
Método para alterar a descrição do anuncio.
Definition at line 98 of file Anuncio.cpp.
References anunciante.
void Anuncio::setCondutor (Membro * membro)
Método para obter os passageiros ja instalados no veiculo.
Definition at line 48 of file Anuncio.cpp.
References condutor.
Referenced by BoleiasInteligentes::showAnunciosMenu().
void Anuncio::setDescricao (const string & descricao)
Método que retorna as coordenadas do local onde termina a Boleia.
Definition at line 88 of file Anuncio.cpp.
References descricao.
void Anuncio::setPreco (const Preco & preco)
Método para alterar o condutor.
Definition at line 53 of file Anuncio.cpp.
References preco.
void Anuncio::setTitulo (const string & titulo)
Método para obter o membro responsavel pelo Anuncio.
Definition at line 23 of file Anuncio.cpp.
References titulo.
void Anuncio::setVeiculo (Veiculo * veiculo)
Método para alterar o titulo.
Definition at line 28 of file Anuncio.cpp.
References veiculo.
void Anuncio::show () const [virtual]
Função para calcular o preço final com todos os custos ja associados.
Reimplemented in AnuncioProcura, and AnuncioOferta.
Definition at line 108 of file Anuncio.cpp.
References anunciante, condutor, dataFim, dataInicio, descricao, Membro::getNome(), hora, preco, Preco::show(), Veiculo::show(), titulo, and veiculo.
Referenced by AnuncioOferta::show(), and AnuncioProcura::show().
void Anuncio::updateConhecidos () [virtual]
Funçao responsavel por determinar se um determinado membro é condutor.Se o for retorna true.
Definition at line 383 of file Anuncio.cpp.
References condutor, and passageiros.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, Anuncio * anuncio) [friend]
Calcula o rsultado final entre os friend points e a distancia para ordenar os anuncios.
Definition at line 397 of file Anuncio.cpp.
Member Data Documentation
Membro* Anuncio::anunciante [protected]
se for igual ao inicio é um evento
Definition at line 28 of file Anuncio.h.
Referenced by criar(), getAnunciante(), load(), save(), setAnunciante(), and show().
Membro* Anuncio::condutor [protected]
Definition at line 29 of file Anuncio.h.
Referenced by calcularFriendPoints(), getCondutor(), isPronto(), load(), podeSerCondutor(), podeSerPassageiro(), save(), setCondutor(), show(), and updateConhecidos().
Data Anuncio::dataFim [protected]
Definition at line 27 of file Anuncio.h.
Referenced by criar(), editar(), getDataFim(), load(), save(), and show().
Data Anuncio::dataInicio [protected]
Número total de pessoas no veículo = passageiros + 1 (condutor)
Definition at line 26 of file Anuncio.h.
Referenced by criar(), editar(), getDataInicio(), load(), save(), and show().
string Anuncio::descricao [protected]
Definition at line 22 of file Anuncio.h.
Referenced by criar(), editar(), getDescricao(), load(), save(), setDescricao(), and show().
Coordenadas Anuncio::destino [protected]
Definition at line 24 of file Anuncio.h.
Referenced by AnuncioOferta::criar(), criar(), editar(), getDestino(), load(), and save().
Hora Anuncio::hora [protected]
Definition at line 32 of file Anuncio.h.
Referenced by criar(), editar(), getHora(), load(), save(), and show().
Coordenadas Anuncio::origem [protected]
Definition at line 23 of file Anuncio.h.
Referenced by AnuncioOferta::criar(), criar(), editar(), getOrigem(), load(), and save().
vector<Particular *> Anuncio::passageiros [protected]
Definition at line 25 of file Anuncio.h.
Referenced by addPassageiro(), calcularFriendPoints(), getPassageiros(), load(), podeSerCondutor(), podeSerPassageiro(), save(), and updateConhecidos().
Preco Anuncio::preco [protected]
Definition at line 31 of file Anuncio.h.
Referenced by AnuncioOferta::AnuncioOferta(), AnuncioOferta::criar(), getPreco(), AnuncioProcura::load(), load(), save(), setPreco(), and show().
string Anuncio::titulo [protected]
Definition at line 21 of file Anuncio.h.
Referenced by criar(), editar(), getTitulo(), load(), save(), setTitulo(), and show().
Veiculo* Anuncio::veiculo [protected]
Definition at line 30 of file Anuncio.h.
Referenced by AnuncioOferta::criar(), getVeiculo(), isPronto(), load(), podeSerPassageiro(), save(), setVeiculo(), and show().
The documentation for this class was generated from the following files:
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Headers/Anuncio.h
C:/Users/Gustavo/git/AEDA-Boleias-Inteligentes/codigo/Source/Anuncio.cpp