var annotated =
[
    [ "Anuncio", "class_anuncio.html", "class_anuncio" ],
    [ "AnuncioIncompletoException", "class_anuncio_incompleto_exception.html", "class_anuncio_incompleto_exception" ],
    [ "AnuncioOferta", "class_anuncio_oferta.html", "class_anuncio_oferta" ],
    [ "AnuncioProcura", "class_anuncio_procura.html", "class_anuncio_procura" ],
    [ "Boleia", "class_boleia.html", "class_boleia" ],
    [ "BoleiasInteligentes", "class_boleias_inteligentes.html", "class_boleias_inteligentes" ],
    [ "Combustivel", "class_combustivel.html", "class_combustivel" ],
    [ "CondutorCandidato", "struct_condutor_candidato.html", "struct_condutor_candidato" ],
    [ "Coordenadas", "class_coordenadas.html", "class_coordenadas" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "DataInvalidaException", "class_data_invalida_exception.html", "class_data_invalida_exception" ],
    [ "Empresa", "class_empresa.html", "class_empresa" ],
    [ "EmptyException", "class_empty_exception.html", "class_empty_exception" ],
    [ "FileException", "class_file_exception.html", "class_file_exception" ],
    [ "Hora", "class_hora.html", "class_hora" ],
    [ "InputUtils", "class_input_utils.html", null ],
    [ "InvalidInputException", "class_invalid_input_exception.html", "class_invalid_input_exception" ],
    [ "LoginException", "class_login_exception.html", "class_login_exception" ],
    [ "Membro", "class_membro.html", "class_membro" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "OutputUtils", "class_output_utils.html", null ],
    [ "PaginaInexistenteException", "class_pagina_inexistente_exception.html", "class_pagina_inexistente_exception" ],
    [ "Particular", "class_particular.html", "class_particular" ],
    [ "Preco", "class_preco.html", "class_preco" ],
    [ "ProibidoException", "class_proibido_exception.html", "class_proibido_exception" ],
    [ "UtilizadorInexistenteException", "class_utilizador_inexistente_exception.html", "class_utilizador_inexistente_exception" ],
    [ "UtilizadorRepetidoException", "class_utilizador_repetido_exception.html", "class_utilizador_repetido_exception" ],
    [ "Veiculo", "class_veiculo.html", "class_veiculo" ],
    [ "ViagemPeriodica", "class_viagem_periodica.html", "class_viagem_periodica" ]
];